[package]
name = "egui-typed-input"
version = "0.1.2"
edition = "2024"
description = "Type safe parsed egui text inputs, with user input checking"
# based on work from SquareMan and BfBB-Clash
authors = ["TimTheBig"]

# same license as egui
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/egui_typed_input"
repository = "https://github.com/TimTheBig/egui_typed_input"

keywords = ["egui", "text_edit", "type_checked", "egui_parse"]
categories = ["gui"]

[dependencies]
egui = { version = ">= 0.32, < 0.34", default-features = false }
thiserror = "2.0"

[dev-dependencies]
eframe = ">= 0.32, < 0.34"
